# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.5-5-gecfb03e
_src_path: https://github.com/algorandfoundation/algokit-beaker-default-template.git
algod_port: '4001'
algod_server: http://localhost
algod_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
author_email: dev@silentrhetoric.com
author_name: SilentRhetoric
ide_vscode: true
indexer_port: '8980'
indexer_server: http://localhost
indexer_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
project_name: hotpotato
python_linter: flake8
use_python_black: true
use_python_mypy: true
use_python_pip_audit: true
use_python_pytest: true

